language: node_js
node_js: 10.16.0
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm

notifications:
  email: false

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
 - yarn install

script:
  - yarn css-main

after_success:
  - yarn test
  - yarn deploy-storybook

before_deploy: |
  PKG_VERSION=$(node -p "require('./package.json').version")
  NPM_TAG="latest"
  if [[ ${PKG_VERSION} =~ -next$ ]]; then
    NPM_TAG="next"
    SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
    UNIQ_PKG_VERSION="${PKG_VERSION}.${SHORT_COMMIT_HASH}"
    npm --no-git-tag-version version ${UNIQ_PKG_VERSION}
  fi

deploy:
  provider: npm
  skip_cleanup: true
  tag: "$NPM_TAG"
  email: jalalazimi@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master