language: node_js
node_js: 10.16.0

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn install

script:
  - yarn css-main

after_success:
  - yarn test
  - yarn deploy-storybook

deploy:
  provider: npm
  skip_cleanup: true
  email: jalalazimi@gmail.com
  api_key: $NPM_TOKEN
